### ISSUE TITLE
How to improve speed?

### ISSUE THREAD

**Issue by SatWiz** [peervpn/peervpn#12]
I really like the simple setup between peers with peervpn. And it is really fast between servers within the same DC. But when I inter connect peer from other places far away (ping time 8 - 10 ms) the transfer speed dramatically drops which makes peervpn not suitable for long distance traffic. I wonder if there is something I can tune? Or is it as designed? See below performance results with iperf.

**INTERNET** performance:
## root@xxxxxxx:~# iperf -c xxx.xxx.xxx.xxx -p 443 -n 20M

Client connecting to xxx.xxx.xxx.xxx, TCP port 443
## TCP window size: 19.6 KByte (default)

[  3] local 192.168.188.254 port 55489 connected with xxx.xxx.xxx.xxx port 443
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0- 0.5 sec  20.0 MBytes   312 Mbits/sec

**PEERVPN** performance:
## root@xxxxxx:~# iperf -c 192.168.11.88 -p 443 -n 20M

Client connecting to 192.168.11.88, TCP port 443
## TCP window size: 19.6 KByte (default)

[  3] local 192.168.11.188 port 47642 connected with 192.168.11.88 port 443
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-148.0 sec  20.0 MBytes  1.13 Mbits/sec

Transfer rate even drops more with scp file copy to around 100kb/s

Is there anything I can do to get closer to internet speed?

**Comment by Ragsboss** [comment]
+1

**Comment by bmullan** [comment]
@SatWiz  - there's no chance your ISP throttles vpn traffic?   I've heard some do for residential connections because they assume some sort of bittorrent going on.    But if you are using a business service then that shouldn't be a possibility.

I didn't do any iperf testing but a year ago I used peervpn to connect servers on AWS, Digital Ocean and here locally and performance was good no matter which server I sent ping's to/from or ftp'd to/from.

**Comment by satter** [comment]
@SatWiz  I've pushed peervpn up to ~600mbit/s on a 1Gbe link, the limit was in CPU performance, 1 core was loaded to 100% on i7-6700.

**Comment by SatWiz** [comment]
Guys, thanks for your feedback. But that is not about. All speed is fine as peers are "close". Issue happens when peers are far away from each. Like 1 peer in France and the other in Netherlands, speed will drop dramaticlly. I have understood L2 is not intend for that big distances. Maybe that counts for this too?

**Comment by bmullan** [comment]
Just out of curiosity & for troubleshooting purposes...

if you do a test using OpenVPN... to any 2 of those SAME sites... what is
the performance?

**Comment by bmullan** [comment]
if you do that test (re using OpenVPN) see how close you can make it apples
to apples (re the level of encryption),  packet size etc.

**Comment by satter** [comment]
@SatWiz for two servers with 55ms RTT over Internet I've got similar performance about 8Mbytes/s

**Comment by bmullan** [comment]
64 Mbps seems decent over the Internet

**Comment by SatWiz** [comment]
@satter what is the file size you send over? Small files indeed same speed but bigger files do you see dropping of speed? Try a iperf speed test like results a post before.

**Comment by satter** [comment]
@SatWiz ~500mb file created from /dev/random

**Comment by bmullan** [comment]
@SatWiz - Don't know why I missed this but I just realized you reduced TCP Window Size to 19.6K byte whereas the "default" is normally 64K byte

Usually for WAN you'd look at increasing Window Size.

This could require tuning for the WAN (re the "Long, Fat Network" - see RFC 1072). 

https://tools.ietf.org/html/rfc1072

The general formula is..
BW-in-bits-per-second * Round-trip-latency-in-seconds = TCP window size in bytes

Because the Internet is a fat pipe going over a distance (distance is really time/latency in this case), the tcp receive window usually needs to be larger not smaller.

**Comment by bmullan** [comment]
@SatWiz - did a google search for a better explanation and this is decent...

http://bradhedlund.com/2008/12/19/how-to-calculate-tcp-throughput-for-long-distance-links/

**Comment by bmullan** [comment]
@satwiz
Did you ever resolve your problem w performance ?

**Comment by SatWiz** [comment]
sorry, I am too bussy with other things and bypassed it with openvpn. Not tried long distance tests with peervpn anymore. I have close this issue for now. Thanks for your comments.

**Comment by bmullan** [comment]
But did you have same reported performance issues with openvpn to/from
those same nodes... is what I was asking.

You seemed to be the only one reporting that kind of issue at the time .?

On Jan 25, 2017 5:44 PM, "Sunny Wu" <notifications@github.com> wrote:

sorry, I am too bussy with other things and bypassed it with openvpn. Not
tried long distance tests with peervpn anymore. I have close this issue for
now. Thanks for your comments.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/peervpn/peervpn/issues/12#issuecomment-275256797>, or mute
the thread

**Comment by SatWiz** [comment]
with openvpn no performance issues at all.

**Comment by bmullan** [comment]
That was with exactly same noes & a reduced 16k vs 64k window size that you
used previously?  re apples to apples
